["defaults"]
exclude = ["format", "spell"]

[[ignore."lwip"]]
files = [
    "lwip/src/include/lwip/sio.h",
    "lwip/src/include/lwip/tcpbase.h",
    "lwip/src/include/lwip/tcpip.h",
    "lwip/src/include/lwip/netdb.h",
    "lwip/src/include/lwip/priv/api_msg.h",
    "lwip/src/include/lwip/priv/altcp_priv.h",
    "lwip/src/include/lwip/priv/tcpip_priv.h",
    "lwip/src/include/lwip/priv/nd6_priv.h",
    "lwip/src/include/lwip/priv/memp_std.h",
    "lwip/src/include/lwip/priv/tcp_priv.h",
    "lwip/src/include/lwip/priv/memp_priv.h",
    "lwip/src/include/lwip/priv/sockets_priv.h",
    "lwip/src/include/lwip/priv/mem_priv.h",
    "lwip/src/include/lwip/priv/raw_priv.h",
    "lwip/src/include/lwip/ethip6.h",
    "lwip/src/include/lwip/nd6.h",
    "lwip/src/include/lwip/igmp.h",
    "lwip/src/include/lwip/tcp.h",
    "lwip/src/include/lwip/altcp_tcp.h",
    "lwip/src/include/lwip/timeouts.h",
    "lwip/src/include/lwip/arch.h",
    "lwip/src/include/lwip/netif.h",
    "lwip/src/include/lwip/ip4.h",
    "lwip/src/include/lwip/mem.h",
    "lwip/src/include/lwip/err.h",
    "lwip/src/include/lwip/raw.h",
    "lwip/src/include/lwip/netifapi.h",
    "lwip/src/include/lwip/if_api.h",
    "lwip/src/include/lwip/udp.h",
    "lwip/src/include/lwip/ip_addr.h",
    "lwip/src/include/lwip/dns.h",
    "lwip/src/include/lwip/etharp.h",
    "lwip/src/include/lwip/dhcp6.h",
    "lwip/src/include/lwip/debug.h",
    "lwip/src/include/lwip/mld6.h",
    "lwip/src/include/lwip/memp.h",
    "lwip/src/include/lwip/ip4_addr.h",
    "lwip/src/include/lwip/ip6.h",
    "lwip/src/include/lwip/icmp.h",
    "lwip/src/include/lwip/ip6_frag.h",
    "lwip/src/include/lwip/def.h",
    "lwip/src/include/lwip/sockets.h",
    "lwip/src/include/lwip/errno.h",
    "lwip/src/include/lwip/inet_chksum.h",
    "lwip/src/include/lwip/altcp.h",
    "lwip/src/include/lwip/ip4_frag.h",
    "lwip/src/include/lwip/dhcp.h",
    "lwip/src/include/lwip/api.h",
    "lwip/src/include/lwip/ip.h",
    "lwip/src/include/lwip/autoip.h",
    "lwip/src/include/lwip/opt.h",
    "lwip/src/include/lwip/pbuf.h",
    "lwip/src/include/lwip/init.h.cmake.in",
    "lwip/src/include/lwip/ip6_addr.h",
    "lwip/src/include/lwip/netbuf.h",
    "lwip/src/include/lwip/inet.h",
    "lwip/src/include/lwip/altcp_tls.h",
    "lwip/src/include/lwip/icmp6.h",
    "lwip/src/include/lwip/snmp.h",
    "lwip/src/include/lwip/sys.h",
    "lwip/src/include/lwip/init.h",
    "lwip/src/include/lwip/prot/nd6.h",
    "lwip/src/include/lwip/prot/igmp.h",
    "lwip/src/include/lwip/prot/tcp.h",
    "lwip/src/include/lwip/prot/ethernet.h",
    "lwip/src/include/lwip/prot/ip4.h",
    "lwip/src/include/lwip/prot/ieee.h",
    "lwip/src/include/lwip/prot/udp.h",
    "lwip/src/include/lwip/prot/dns.h",
    "lwip/src/include/lwip/prot/etharp.h",
    "lwip/src/include/lwip/prot/dhcp6.h",
    "lwip/src/include/lwip/prot/mld6.h",
    "lwip/src/include/lwip/prot/iana.h",
    "lwip/src/include/lwip/prot/ip6.h",
    "lwip/src/include/lwip/prot/icmp.h",
    "lwip/src/include/lwip/prot/dhcp.h",
    "lwip/src/include/lwip/prot/ip.h",
    "lwip/src/include/lwip/prot/autoip.h",
    "lwip/src/include/lwip/prot/icmp6.h",
    "lwip/src/include/lwip/apps/tftp_server.h",
    "lwip/src/include/lwip/apps/snmp_opts.h",
    "lwip/src/include/lwip/apps/snmpv3.h",
    "lwip/src/include/lwip/apps/snmp_mib2.h",
    "lwip/src/include/lwip/apps/altcp_tls_mbedtls_opts.h",
    "lwip/src/include/lwip/apps/smtp.h",
    "lwip/src/include/lwip/apps/http_client.h",
    "lwip/src/include/lwip/apps/mdns_opts.h",
    "lwip/src/include/lwip/apps/httpd_opts.h",
    "lwip/src/include/lwip/apps/snmp_core.h",
    "lwip/src/include/lwip/apps/mqtt_priv.h",
    "lwip/src/include/lwip/apps/sntp_opts.h",
    "lwip/src/include/lwip/apps/netbiosns_opts.h",
    "lwip/src/include/lwip/apps/snmp_snmpv2_framework.h",
    "lwip/src/include/lwip/apps/snmp_threadsync.h",
    "lwip/src/include/lwip/apps/lwiperf.h",
    "lwip/src/include/lwip/apps/mqtt_opts.h",
    "lwip/src/include/lwip/apps/mqtt.h",
    "lwip/src/include/lwip/apps/snmp_table.h",
    "lwip/src/include/lwip/apps/netbiosns.h",
    "lwip/src/include/lwip/apps/tftp_opts.h",
    "lwip/src/include/lwip/apps/snmp_snmpv2_usm.h",
    "lwip/src/include/lwip/apps/mdns_priv.h",
    "lwip/src/include/lwip/apps/sntp.h",
    "lwip/src/include/lwip/apps/smtp_opts.h",
    "lwip/src/include/lwip/apps/httpd.h",
    "lwip/src/include/lwip/apps/altcp_proxyconnect.h",
    "lwip/src/include/lwip/apps/mdns.h",
    "lwip/src/include/lwip/apps/FILES",
    "lwip/src/include/lwip/apps/snmp.h",
    "lwip/src/include/lwip/apps/snmp_scalar.h",
    "lwip/src/include/lwip/apps/fs.h",
    "lwip/src/include/lwip/ip6_zone.h",
    "lwip/src/include/lwip/stats.h",
    "lwip/src/include/netif/ppp/ppp_impl.h",
    "lwip/src/include/netif/ppp/pppol2tp.h",
    "lwip/src/include/netif/ppp/pppos.h",
    "lwip/src/include/netif/ppp/chap_ms.h",
    "lwip/src/include/netif/ppp/pppcrypt.h",
    "lwip/src/include/netif/ppp/chap-md5.h",
    "lwip/src/include/netif/ppp/pppdebug.h",
    "lwip/src/include/netif/ppp/ipv6cp.h",
    "lwip/src/include/netif/ppp/eap.h",
    "lwip/src/include/netif/ppp/ecp.h",
    "lwip/src/include/netif/ppp/ppp_opts.h",
    "lwip/src/include/netif/ppp/eui64.h",
    "lwip/src/include/netif/ppp/ppp.h",
    "lwip/src/include/netif/ppp/mppe.h",
    "lwip/src/include/netif/ppp/pppoe.h",
    "lwip/src/include/netif/ppp/lcp.h",
    "lwip/src/include/netif/ppp/fsm.h",
    "lwip/src/include/netif/ppp/magic.h",
    "lwip/src/include/netif/ppp/ipcp.h",
    "lwip/src/include/netif/ppp/upap.h",
    "lwip/src/include/netif/ppp/pppapi.h",
    "lwip/src/include/netif/ppp/vj.h",
    "lwip/src/include/netif/ppp/polarssl",
    "lwip/src/include/netif/ppp/polarssl/md5.h",
    "lwip/src/include/netif/ppp/polarssl/sha1.h",
    "lwip/src/include/netif/ppp/polarssl/des.h",
    "lwip/src/include/netif/ppp/polarssl/arc4.h",
    "lwip/src/include/netif/ppp/polarssl/md4.h",
    "lwip/src/include/netif/ppp/ccp.h",
    "lwip/src/include/netif/ppp/chap-new.h",
    "lwip/src/include/netif/lowpan6_opts.h",
    "lwip/src/include/netif/ethernet.h",
    "lwip/src/include/netif/etharp.h",
    "lwip/src/include/netif/zepif.h",
    "lwip/src/include/netif/bridgeif.h",
    "lwip/src/include/netif/lowpan6_ble.h",
    "lwip/src/include/netif/lowpan6.h",
    "lwip/src/include/netif/lowpan6_common.h",
    "lwip/src/include/netif/bridgeif_opts.h",
    "lwip/src/include/netif/slipif.h",
    "lwip/src/include/netif/ieee802154.h",
    "lwip/src/include/compat/stdc/errno.h",
    "lwip/src/include/compat/posix/net/if.h",
    "lwip/src/include/compat/posix/netdb.h",
    "lwip/src/include/compat/posix/sys/socket.h",
    "lwip/src/include/compat/posix/arpa/inet.h",
    "lwip/src/api/sockets.c",
    "lwip/src/api/netifapi.c",
    "lwip/src/api/err.c",
    "lwip/src/api/tcpip.c",
    "lwip/src/api/api_lib.c",
    "lwip/src/api/api_msg.c",
    "lwip/src/api/netbuf.c",
    "lwip/src/api/if_api.c",
    "lwip/src/api/netdb.c",
    "lwip/src/netif/ppp/lcp.c",
    "lwip/src/netif/ppp/pppol2tp.c",
    "lwip/src/netif/ppp/magic.c",
    "lwip/src/netif/ppp/eui64.c",
    "lwip/src/netif/ppp/ipv6cp.c",
    "lwip/src/netif/ppp/pppapi.c",
    "lwip/src/netif/ppp/upap.c",
    "lwip/src/netif/ppp/ipcp.c",
    "lwip/src/netif/ppp/ccp.c",
    "lwip/src/netif/ppp/ppp.c",
    "lwip/src/netif/ppp/eap.c",
    "lwip/src/netif/ppp/mppe.c",
    "lwip/src/netif/ppp/chap-new.c",
    "lwip/src/netif/ppp/pppcrypt.c",
    "lwip/src/netif/ppp/chap_ms.c",
    "lwip/src/netif/ppp/pppos.c",
    "lwip/src/netif/ppp/utils.c",
    "lwip/src/netif/ppp/multilink.c",
    "lwip/src/netif/ppp/auth.c",
    "lwip/src/netif/ppp/chap-md5.c",
    "lwip/src/netif/ppp/fsm.c",
    "lwip/src/netif/ppp/ecp.c",
    "lwip/src/netif/ppp/demand.c",
    "lwip/src/netif/ppp/vj.c",
    "lwip/src/netif/ppp/polarssl",
    "lwip/src/netif/ppp/polarssl/md4.c",
    "lwip/src/netif/ppp/polarssl/sha1.c",
    "lwip/src/netif/ppp/polarssl/md5.c",
    "lwip/src/netif/ppp/polarssl/arc4.c",
    "lwip/src/netif/ppp/polarssl/des.c",
    "lwip/src/netif/ppp/pppoe.c",
    "lwip/src/netif/lowpan6.c",
    "lwip/src/netif/lowpan6_ble.c",
    "lwip/src/netif/zepif.c",
    "lwip/src/netif/ethernet.c",
    "lwip/src/netif/lowpan6_common.c",
    "lwip/src/netif/slipif.c",
    "lwip/src/netif/bridgeif.c",
    "lwip/src/netif/bridgeif_fdb.c",
    "lwip/src/core/ip.c",
    "lwip/src/core/udp.c",
    "lwip/src/core/tcp.c",
    "lwip/src/core/altcp_tcp.c",
    "lwip/src/core/def.c",
    "lwip/src/core/ipv6/icmp6.c",
    "lwip/src/core/ipv6/dhcp6.c",
    "lwip/src/core/ipv6/nd6.c",
    "lwip/src/core/ipv6/inet6.c",
    "lwip/src/core/ipv6/ethip6.c",
    "lwip/src/core/ipv6/mld6.c",
    "lwip/src/core/ipv6/ip6.c",
    "lwip/src/core/ipv6/ip6_frag.c",
    "lwip/src/core/ipv6/ip6_addr.c",
    "lwip/src/core/dns.c",
    "lwip/src/core/raw.c",
    "lwip/src/core/netif.c",
    "lwip/src/core/ipv4/ip4_frag.c",
    "lwip/src/core/ipv4/icmp.c",
    "lwip/src/core/ipv4/ip4_addr.c",
    "lwip/src/core/ipv4/etharp.c",
    "lwip/src/core/ipv4/ip4.c",
    "lwip/src/core/ipv4/igmp.c",
    "lwip/src/core/ipv4/autoip.c",
    "lwip/src/core/ipv4/dhcp.c",
    "lwip/src/core/stats.c",
    "lwip/src/core/tcp_in.c",
    "lwip/src/core/tcp_out.c",
    "lwip/src/core/pbuf.c",
    "lwip/src/core/inet_chksum.c",
    "lwip/src/core/memp.c",
    "lwip/src/core/altcp.c",
    "lwip/src/core/sys.c",
    "lwip/src/core/init.c",
    "lwip/src/core/altcp_alloc.c",
    "lwip/src/core/timeouts.c",
    "lwip/src/core/mem.c"
]

[[ignore."embeddedsw"]]
files = [
    "embeddedsw/ThirdParty/sw_services/lwip211/src/contrib/ports/xilinx/include/netif/xtopology.h",
    "embeddedsw/ThirdParty/sw_services/lwip211/src/contrib/ports/xilinx/include/netif/xadapter.h",
    "embeddedsw/ThirdParty/sw_services/lwip211/src/contrib/ports/xilinx/include/netif/xpqueue.h",
    "embeddedsw/ThirdParty/sw_services/lwip211/src/contrib/ports/xilinx/include/netif/xemacpsif.h",
    "embeddedsw/ThirdParty/sw_services/lwip211/src/contrib/ports/xilinx/netif/xpqueue.c",
    "embeddedsw/ThirdParty/sw_services/lwip211/src/contrib/ports/xilinx/netif/xemacpsif_dma.c",
    "embeddedsw/ThirdParty/sw_services/lwip211/src/contrib/ports/xilinx/netif/xemac_ieee_reg.h",
    "embeddedsw/ThirdParty/sw_services/lwip211/src/contrib/ports/xilinx/netif/xemacpsif_physpeed.c",
    "embeddedsw/ThirdParty/sw_services/lwip211/src/contrib/ports/xilinx/netif/xadapter.c",
    "embeddedsw/ThirdParty/sw_services/lwip211/src/contrib/ports/xilinx/netif/xemacpsif.c",
    "embeddedsw/ThirdParty/sw_services/lwip211/src/contrib/ports/xilinx/netif/xemacpsif_hw.c",
    "embeddedsw/XilinxProcessorIPLib/drivers/emacps/src/xemacps_bdring.h",
    "embeddedsw/XilinxProcessorIPLib/drivers/emacps/src/xemacps_bd.h",
    "embeddedsw/XilinxProcessorIPLib/drivers/emacps/src/xemacps.h",
    "embeddedsw/XilinxProcessorIPLib/drivers/emacps/src/xemacps_intr.c",
    "embeddedsw/XilinxProcessorIPLib/drivers/emacps/src/xemacps_hw.h",
    "embeddedsw/XilinxProcessorIPLib/drivers/emacps/src/xemacps.c",
    "embeddedsw/XilinxProcessorIPLib/drivers/emacps/src/xemacps_control.c",
    "embeddedsw/XilinxProcessorIPLib/drivers/emacps/src/xemacps_bdring.c",
    "embeddedsw/XilinxProcessorIPLib/drivers/scugic/src/xscugic.h",
    "embeddedsw/XilinxProcessorIPLib/drivers/scugic/src/xscugic_hw.h",
]

[[ignore."embeddedsw"]]
files = [
    "cpsw/src/delay.c",
    "cpsw/src/perf.c",
    "cpsw/src/include/hw_cpsw_sl.h",
    "cpsw/src/include/hw_mdio.h",
    "cpsw/src/include/lwiplib.h",
    "cpsw/src/include/hw_types.h",
    "cpsw/src/include/lwip_bbb.h",
    "cpsw/src/include/locator.h",
    "cpsw/src/include/hw_cm_per.h",
    "cpsw/src/include/cp15.h",
    "cpsw/src/include/mmu.h",
    "cpsw/src/include/hw_cpsw_wr.h",
    "cpsw/src/include/phy.h",
    "cpsw/src/include/hw_cpsw_ss.h",
    "cpsw/src/include/soc_AM335x.h",
    "cpsw/src/include/beaglebone.h",
    "cpsw/src/include/hw_cpsw_port.h",
    "cpsw/src/include/netif/FILES",
    "cpsw/src/include/netif/cpswif.h",
    "cpsw/src/include/hw_cpsw_ale.h",
    "cpsw/src/include/cpsw.h",
    "cpsw/src/include/cache.h",
    "cpsw/src/include/hw_cpsw_cpdma.h",
    "cpsw/src/include/FILES",
    "cpsw/src/include/mdio.h",
    "cpsw/src/include/delay.h",
    "cpsw/src/include/hw_control_AM335x.h",
    "cpsw/src/locator.c",
    "cpsw/src/lwiplib.c",
    "cpsw/src/netif/delay.c",
    "cpsw/src/netif/cpsw_bb.c",
    "cpsw/src/netif/mmu.c",
    "cpsw/src/netif/cpsw.c",
    "cpsw/src/netif/cache.c",
    "cpsw/src/netif/cpswif.c",
    "cpsw/src/netif/phy.c",
    "cpsw/src/netif/FILES",
    "cpsw/src/netif/mdio.c",
    "cpsw/src/netif/cp15.S",
]
