["defaults"]
exclude = ["format", "spell"]

[[ignore."lwip"]]
files = [
    "lwip/src/include/lwip/*",
    "lwip/src/include/lwip/priv/*",
    "lwip/src/include/lwip/prot/*",
    "lwip/src/include/lwip/apps/*",
    "lwip/src/include/lwip/*",
    "lwip/src/include/netif/ppp/*",
    "lwip/src/include/netif/ppp/polarssl/*",
    "lwip/src/include/netif/*",
    "lwip/src/include/compat/stdc/errno.h",
    "lwip/src/include/compat/posix/net/if.h",
    "lwip/src/include/compat/posix/netdb.h",
    "lwip/src/include/compat/posix/sys/socket.h",
    "lwip/src/include/compat/posix/arpa/inet.h",
    "lwip/src/api/*",
    "lwip/src/netif/ppp/*",
    "lwip/src/netif/ppp/polarssl/*",
    "lwip/src/netif/*",
    "lwip/src/core/*",
    "lwip/src/core/ipv6/*",
    "lwip/src/core/ipv4/*"
]

[[ignore."embeddedsw"]]
files = [
    "embeddedsw/ThirdParty/sw_services/lwip211/src/contrib/ports/xilinx/include/netif/*",
    "embeddedsw/ThirdParty/sw_services/lwip211/src/contrib/ports/xilinx/netif/*",
    "embeddedsw/XilinxProcessorIPLib/drivers/emacps/src/*",
    "embeddedsw/XilinxProcessorIPLib/drivers/scugic/src/*",
]

[[ignore."cpsw"]]
files = [
    "cpsw/src/*",
    "cpsw/src/include/*",
    "cpsw/src/include/netif/*",
    "cpsw/src/netif/*"
]
